export const POPULAR_FILMS_REQUEST = 'POPULAR_FILMS_REQUEST';
export const POPULAR_FILMS_SUCCESS = 'POPULAR_FILMS_SUCCESS';
export const POPULAR_FILMS_FAIL = 'POPULAR_FILMS_FAIL';


export const MORE_POPULAR_FILMS_REQUEST = 'MORE_POPULAR_FILMS_REQUEST';
export const MORE_POPULAR_FILMS_SUCCESS = 'MORE_POPULAR_FILMS_SUCCESS';
export const MORE_POPULAR_FILMS_FAIL = 'MORE_POPULAR_FILMS_FAIL';