export const FILM_INFO_REQUEST = 'FILM_INFO_REQUEST';
export const FILM_INFO_SUCCESS = 'FILM_INFO_SUCCESS';
export const FILM_INFO_FAIL = 'FILM_INFO_FAIL';
export const TRAILER_REQUEST = 'TRAILER_REQUEST';
export const TRAILER_SUCCESS = 'TRAILER_SUCCESS';
export const TRAILER_FAIL = 'TRAILER_FAIL';