export const GENERS_REQUEST = 'GENERS_REQUEST';
export const GENERS_SUCCESS = 'GENERS_SUCCESS';
export const GENERS_FAIL = 'GENERS_FAIL';

export const LIST_GENERS_REQUEST = 'LIST_GENERS_REQUEST';
export const LIST_GENERS_SUCCESS = 'LIST_GENERS_SUCCESS';
export const LIST_GENERS_FAIL = 'LIST_GENERS_FAIL';

export const MORE_LIST_GENERS_REQUEST = 'MORE_LIST_GENERS_REQUEST';
export const MORE_LIST_GENERS_SUCCESS = 'MORE_LIST_GENERS_SUCCESS';
export const MORE_LIST_GENERS_FAIL = 'MORE_LIST_GENERS_FAIL';