export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const MORE_SEARCH_REQUEST = 'MORE_SEARCH_REQUEST';
export const MORE_SEARCH_SUCCESS = 'MORE_SEARCH_SUCCESS';
export const MORE_SEARCH_FAIL = 'MORE_SEARCH_FAIL';