export const TOP_FILMS_REQUEST = 'TOP_FILMS_REQUEST';
export const TOP_FILMS_SUCCESS = 'TOP_FILMS_SUCCESS';
export const TOP_FILMS_FAIL = 'TOP_FILMS_FAIL';


export const MORE_TOP_FILMS_REQUEST = 'MORE_TOP_FILMS_REQUEST';
export const MORE_TOP_FILMS_SUCCESS = 'MORE_TOP_FILMS_SUCCESS';
export const MORE_TOP_FILMS_FAIL = 'MORE_TOP_FILMS_FAIL';